### ISSUE TITLE
concern tr1_utils.pas

### ISSUE THREAD

**Issue by DarkAgesGeek** [skalogryz/larasbraid#1]
Dear Skalogryz
Reading your source tr1_utils.pas, i think there is a tiny mistake around line 648, a copy is embeded here
<
lvl.AnimDispCount:=s.ReadDWord;

  if TR1Debug then

    writeln('anim disp: ', lvl.AnimationCount,' ',sizeof(tr_anim_dispatch));

> 
lvl.AnimationCount should be replaced by lvl.AnimDispCount in the writeln instruction.
Did i get it right?
please excuse my English, my mothers tongue is french

Cheers

**Comment by skalogryz** [comment]
Thank you! you're absolutely right!

sorry for the late response!

**Comment by skalogryz** [comment]
the code has been fixed

**Comment by DarkAgesGeek** [comment]
Tank you for your answer, You code was really helpfull for me. Trying to understand all these structures in a level data file.
Happy new Year

    Le ‎jeudi‎ ‎28‎ ‎décembre‎ ‎2017‎ ‎18‎:‎41‎:‎21‎ ‎CET, Dmitry Boyarintsev <notifications@github.com> a écrit :  
 
 
Thank you! you're absolutely right!

sorry for the late response!
